import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const target = resolve(root, "extension/public/THIRD_PARTY_NOTICES.txt");
const check = process.argv.includes("--check");
const EXTRA = [
  "COPYRIGHT",
  "LICENSE-THIRD-PARTY",
  "LICENSE-UNICODE",
  "LICENSE-WHATWG",
];

type Package = {
  name: string;
  version: string;
  license: string | null;
  repository: string | null;
  manifest_path: string;
};

const cargo = (...args: string[]) =>
  execFileSync("cargo", args, {
    cwd: root,
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  });

const linked = new Set(
  cargo(
    "tree",
    "--locked",
    "-p",
    "culverin-counter",
    "--target",
    "wasm32-unknown-unknown",
    "-e",
    "normal,no-proc-macro",
    "--prefix",
    "none",
    "--format",
    "{p}",
  )
    .split("\n")
    .map((line) => line.replace(/ \(\*\)$/, "").split(" "))
    .filter(([name]) => name && name !== "culverin-counter")
    .map(([name, version]) => `${name} ${version!.slice(1)}`),
);
const metadata = JSON.parse(
  cargo(
    "metadata",
    "--locked",
    "--format-version",
    "1",
    "--filter-platform",
    "wasm32-unknown-unknown",
  ),
) as { packages: Package[] };
const packages = metadata.packages
  .filter((item) => linked.has(`${item.name} ${item.version}`))
  .sort((a, b) =>
    a.name === b.name
      ? a.version.localeCompare(b.version)
      : a.name.localeCompare(b.name),
  );
if (packages.length !== linked.size) {
  console.error("could not resolve metadata for every linked crate");
  process.exit(1);
}

function licenseFiles(item: Package): { used: string; files: string[] } {
  const directory = dirname(item.manifest_path);
  const names = readdirSync(directory);
  const expression = (item.license ?? "").replaceAll("/", " OR ");
  const found = (pattern: RegExp) => names.filter((name) => pattern.test(name));
  let used: string;
  let files: string[];
  if (/\bMIT\b/.test(expression)) {
    used = "MIT";
    files = found(/^LICEN[CS]E-MIT(\.md|\.txt)?$/);
    if (!files.length && expression === "MIT") files = found(/^LICENSE$/);
  } else if (expression === "MPL-2.0") {
    used = "MPL-2.0";
    files = found(/^LICENSE$/);
  } else {
    throw new Error(`${item.name} has an unsupported license: ${expression}`);
  }
  if (!files.length)
    throw new Error(`${item.name} ${item.version} has no ${used} license file`);
  files.push(...EXTRA.filter((name) => names.includes(name)));
  return { used, files: files.map((name) => join(directory, name)) };
}

const sections = packages.map((item) => {
  const { used, files } = licenseFiles(item);
  const header = [
    `${item.name} ${item.version}`,
    `License: ${item.license} (used under ${used})`,
    ...(item.repository ? [`Source: ${item.repository}`] : []),
  ];
  if (used === "MPL-2.0")
    header.push(
      `The source code of this component is available at https://crates.io/crates/${item.name}/${item.version}.`,
    );
  const texts = files.map((file) => readFileSync(file, "utf8").trim());
  return [...header, "", ...texts].join("\n");
});

const notices = `${[
  "Culverin third-party notices\n\nCulverin is licensed under the Apache License 2.0. Its WebAssembly line counter includes the following Rust crates, and the packaged JavaScript glue for that counter is generated by wasm-bindgen.",
  ...sections,
].join(`\n\n${"-".repeat(72)}\n\n`)}\n`;

if (check) {
  if (!existsSync(target) || readFileSync(target, "utf8") !== notices) {
    console.error(
      "THIRD_PARTY_NOTICES.txt is out of date; run bun run notices:build",
    );
    process.exit(1);
  }
} else {
  writeFileSync(target, notices);
  console.log(`${packages.length} crates written to ${target}`);
}
